config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resource :user

  resources :favorites, only: [:index, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #アソシエーション
  belongs_to :picture
  belongs_to :user

end

app/models/picture.rb
class Picture < ApplicationRecord
  #アソシエーション
  belongs_to :user
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { in: 1..20 }
  validates :content, presence: true, length: { in: 1..200 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  #アソシエーション
  has_many :pictures
  has_many :favorites, dependent: :destroy

  #Validationの追加
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  has_secure_password
  validates :password, length: { minimum: 6 }

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  #loginチェック
  before_action :login_required

  def login_required
    unless current_user
      flash[:notice] = 'ログインが必要です。'
       redirect_to new_session_path unless current_user
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorites
  end

  def create
    current_user.favorites.create(picture_id: params[:picture_id])
    picture =
    redirect_to pictures_url, notice: "#{Picture.find(params[:picture_id]).user.name}さんの写真をお気に入り登録しました"
 end

 def destroy
    current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{Picture.find(params[:picture_id]).user.name}さんの写真をお気に入り解除しました"
 end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :destroy]
  before_action :user_check, only: [:edit,:update,:destroy]

  def index
    @pictures = Picture.all.order(created_at: "DESC")
    @favorites = current_user.favorites
  end

  def show
    @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = current_user.pictures.build(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      ContactMailer.contact_mail(@picture).deliver  ##追記
      redirect_to pictures_path, notice: "タイムラインを投稿しました！"
    else
      render action: :new
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "タイムラインを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"タイムラインを削除しました！"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def set_picture
    @picture = current_user.pictures.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :content, :image,:image_cache)
  end

    #pictureを投稿したユーザとログインユーザが同一でない場合はトップページに戻るTrueを返す
  def user_check
    unless @picture.user.id == current_user.id
      flash[:notice] = '編集・削除できません'
      redirect_to pictures_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
    if session[:user_id]
      redirect_to pictures_path
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:show,:edit,:update]
  skip_before_action :login_required, only:[:new, :create]

  def new
    if session[:user_id]
      redirect_to pictures_path
    end
     @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to pictures_path, notice: "会員登録が完了しました。"
    else
      render 'new'
    end
  end

  def edit
  end

  #アップデートアクション
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "会員情報を変更しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image)
  end

  def user_find
    @user= current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/views/favorites/index.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- タイムライン表示画面 -->
    <div class="col-md-9">
      <h4>お気に入り一覧</h4>
      <!-- つぶやき一覧を表示する -->
      <div class="row row-eq-height">
        <div class = "pictures">
          <% if @favorites.empty? %>
          <h5> お気に入りの写真はありません</h5>
          <% else %>
            <% @favorites.each {|favorite| %>
              <% picture = Picture.find_by(id: favorite.picture_id) %>
                <div class="col-md-4">
                  <div class="picture">
                    <div class="picture-data clearfix">
                      <div class="profile-img">
                        <img src="<%=picture.user.image%>" alt="">
                      </div>
                      <span class="picture-title"><%= picture.user.name %></span>
                      <span class="create-date"><%= picture.created_at.strftime("%Y年%m月%d日") %></span>
                    </div>
                    <div class="picture-content">
                      <p>タイトル : <%= picture.title %></p>
                      <p>内容: <%= picture.content %></p>
                    </div>
                    <div class="picture-img">
                      <% if picture.image && picture.image.url %>
                        <img src="<%=picture.image%>" alt="">
                      <% else %>
                        <%= image_tag('no_image.png') %>
                      <% end %>
                    </div>
                    <div class="picture-edit clearfix">
                      <a href="/pictures/<%=picture.id%>"><i class="fas fa-info-circle fa-color"></i></a>
                      <% @favorite = @favorites.find_by(picture_id: picture.id) %>
                      <a href="/favorites/<%=@favorite.id%>?picture_id=<%=picture.id%>" data-method=delete><i class="fas fa-heart fa-color"></i></a>
                    </div>
                  </div>
                </div>
            <% } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IGclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/pictures"> <%= image_tag('instagram.png') %></a>
            <a class="navbar-brand" href="/pictures">Instagram</a>
          </div>

          <div class="collapse navbar-collapse navbar-right" id="navbarEexample1">
            <ul class="nav navbar-nav float-right">
              <% if current_user then %>
              <p class="navbar-text"><%= link_to "#{current_user.name}", user_path(current_user.id) %></p>
              <li ><p class="navbar-text"><%= link_to "新規投稿", new_picture_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "投稿写真一覧", pictures_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "お気に入り一覧", favorites_path %></p></li>
              <li><p class="navbar-text"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></p></li>
              <% else %>
              <li ><p class="navbar-text"><%= link_to "新規登録", new_user_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "ログイン", new_session_path %></p></li>
              <% end %>
            </ul>
          </div>
        </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <div class="main">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> エラーが発生しました:</h2>
      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="row">
      <div class="form-group col-md-6">
        <label>タイトル</label>
        <input type="text" class="form-control" name="picture[title]" value="<%=@picture.title%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>内容</label>
        <textarea class="form-control" name="picture[content]" rows="5"><%=@picture.content%></textarea>
      </div>
    </div>

    <div class="form-row">
      <div class="picture-image">
        <div class="form-group">
          <label>画像</label>
          <!-- 確認画面から新規作成画面に戻った時に、 -->
          <!-- アップロードした画像を表示させるための記述 -->
          <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
          <%= form.file_field :image %>
          <%= form.hidden_field :image_cache %>
        </div>
      </div>
    </div>


    <button type="submit" class="btn btn-primary" name="commit">投稿する</button>
  </form>
<% end %>

app/views/pictures/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4>以下の内容で、送信する。</h4>

      <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>

        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image %>
        <%= form.hidden_field :image_cache %>

      <form>
        <div class="row">
          <div class="form-group col-md-6">
            <label>タイトル</label>
            <input type="text" readonly class="form-control" name="picture[title]" value="<%=@picture.title%>">
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-6">
            <label>内容</label>
              <textarea readonly class="form-control" name="picture[content]" rows="5"><%=@picture.content%></textarea>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <label>画像</label>
            <div class="img-fluid">
            <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-6">
            <label>ユーザ名</label>
            <input type="text" readonly class="form-control" value="<%= @picture.user.name %>">
          </div>
        </div>
        <button type="submit" class="btn btn-primary" name="commit">投稿する</button>
        <% end %>

        <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
          <%= form.hidden_field :title %>
          <%= form.hidden_field :content %>
          <%= form.hidden_field :image %>
          <%= form.hidden_field :image_cache %>
          <button type="submit" class="btn btn-primary" name="back">戻る</button>
        <% end %>
      </form>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4>投稿画像の編集</h4>
      <%= render 'form', picture: @picture %>
      <a href="/pictures/<%=@picture.id%>"><button class="btn btn-primary btn-sm" type="submit">詳細画面</button></a>
      <a href="/pictures"><button class="btn btn-primary  btn-sm" type="submit">投稿画像一覧</button></a>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container-fluid">
  <div class="row">

    <!-- タイムライン表示画面 -->
    <div class="col-md-9">
      <h4>投稿一覧</h4>
      <!-- つぶやき一覧を表示する -->
      <div class="row row-eq-height">
        <% @pictures.each {|picture| %>
          <div class="col-md-4">
            <div class="picture">
              <div class="picture-data clearfix">
                <div class="profile-img">
                  <img src="<%=picture.user.image%>" alt="">
                </div>
                <span class="picture-title"><%= picture.user.name %></span>
                <span class="create-date"><%= picture.created_at.strftime("%Y年%m月%d日") %></span>
              </div>
              <div class="picture-content">
                <p>タイトル : <%= picture.title %></p>
                <p>内容: <%= picture.content %></p>
              </div>
              <div class="picture-img">
                <% if picture.image && picture.image.url %>
                <img src="<%=picture.image%>" alt="">
                <% else %>
                <%= image_tag('no_image.png') %>
                <% end %>
              </div>
              <div class="picture-edit clearfix">
                <a href="/pictures/<%=picture.id%>"><i class="fas fa-info-circle fa-color"></i></a>
                <% if picture.user.id == current_user.id %>
                  <a href="/pictures/<%=picture.id%>/edit" data-confirm="本当に編集してよろしいですか"><i class="far fa-edit fa-color"></i></a>
                  <a href="/pictures/<%=picture.id%>" data-confirm="本当に削除してよろしいですか" data-method=delete><i class="fas fa-trash-alt fa-color"></i></a>
                <% end %>
                <% unless picture.user_id == current_user.id %>
                  <% if @favorites.find_by(picture_id: picture.id).present? %>
                    <% @favorite = @favorites.find_by(picture_id: picture.id) %>
                    <a href="/favorites/<%=@favorite.id%>?picture_id=<%=picture.id%>" data-method=delete><i class="fas fa-heart fa-color"></i></a>
                  <% else %>
                    <a href="/favorites?picture_id=<%=picture.id %>" data-method=post><i class="far fa-heart fa-color"></i></a>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% } %>
      </div>
    </div>

    <!-- 友達リスト表示 -->
    <div class="col-md-2">
      <h4>お気に入り</h4>
      <div class="sidemenu">
        <ul>
          <% current_user.favorites.each do |favorite| %>
          <% picture = @pictures.find(favorite.picture_id) %>
            <a href="/pictures/<%=picture.id%>">
              <li>
                <div class="friend-img clearfix">
                  <% if picture.image.url %>
                    <%= image_tag picture.image.url %>
                  <% else %>
                    <%= image_tag('no_image.png') %>
                  <% end %>
                </div>
                <div class="frien-name">
                  <%= picture.title %>
                </div>
              </li>
            </a>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h4>写真投稿</h4>
        <%= render 'form', picture: @picture %>
        <a href="/pictures"><button class="btn btn-primary" type="submit">戻る</button></a>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class = "pictures">
        <div class="picture">
          <div class="picture-data clearfix">
            <div class="profile-img">
              <img src="<%=@picture.user.image%>" alt="">
            </div>
            <span class="picture-title"><%= @picture.user.name %></span>
            <span class="create-date"><%= @picture.created_at %></span>
          </div>
          <div class="picture-content">
            <p>タイトル : <%= @picture.title %></p>
            <p>内容: <%= @picture.content %></p>
          </div>
          <div class="picture-img">
            <img src="<%=@picture.image%>" alt="" class="picture-image">
          </div>
          <div class="picture-edit clearfix">
            <%= link_to '戻る', pictures_path %>
            <% if @picture.user.id == current_user.id then %>
              <a href="/pictures/<%=@picture.id%>/edit" data-confirm="本当に編集してよろしいですか"><i class="far fa-edit fa-color"></i></a>
              <a href="/pictures/<%=@picture.id%>" data-confirm="本当に削除してよろしいですか" data-method=delete><i class="fas fa-trash-alt fa-color"></i>
            <% end %>
            <% unless @picture.user_id == current_user.id %>
              <% if @favorite.present? %>
                <a href="/favorites/<%=@favorite.id%>" data-method=delete><i class="fas fa-heart fa-color"></i>
              <% else %>
                <a href="/favorites?picture_id=<%=@picture.id %>" data-method=post><i class="far fa-heart fa-color"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model:user, local: true,url: user_path) do |f| %>

  <form>
    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ名</label>
        <input type="text" class="form-control" name="user[name]" value="<%=@user.name%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Eメール</label>
        <input type="text" class="form-control" name="user[email]" value="<%=@user.email%>">
      </div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label>プロフィール画像</label>
        <div class="img-profile">
          <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>パスワード</label>
        <input type="password" class="form-control" name="user[password]" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>パスワード確認</label>
        <input type="password" class="form-control" name="user[password_confirmation]" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-1">
        <button type="submit" class="btn btn-primary" name="commit">登録</button>
      </div>
    </div>
  </form>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h4>会員情報編集</h4>
  <%= render 'form', user: @user %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h4>会員登録</h4>
  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h4>ユーザ情報</h4>
  <form>
    <div class="row">
      <div class="col-md-6">
        <label>画像</label>
        <div class="img-profile">
          <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ名</label>
        <input type="text" readonly class="form-control" name="user[name]" value="<%=@user.name%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Eメール</label>
        <input type="text" readonly class="form-control" name="user[email]" value="<%=@user.email%>">
      </div>
    </div>

    <% if @user.id == current_user.id then %>
      <%= link_to '編集', edit_user_path(@user) %>
    <% end %>
  </form>
</div>